--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#f4f1f0"
foreground="#52505e"
cursor="#52505e"

-- Colors
color0="#f4f1f0"
color1="#a01c10"
color2="#0b5d46"
color3="#545422"
color4="#1c4f9f"
color5="#942166"
color6="#185870"
color7="#52505e"
color8="#575050"
color9="#913210"
color10="#2a5d08"
color11="#774611"
color12="#5440a7"
color13="#8d0e9b"
color14="#0e577b"
color15="#52505e"
