name: build-config
on:
  push:
    branches:
      - master
      - wayland
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-home-manager-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
      - name: Install Nix
        uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: rprecenth
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
      - name: Build config
        run: >
          cachix watch-exec rprecenth nix -- run github:Mic92/nix-fast-build -- --no-nom --skip-cached --flake .#homeConfigurations."rasmus@kalmiya".activationPackage
