name: build-config
on:
  push:
    branches:
      - master
      - wayland
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-home-manager-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: rprecenth
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
      - name: Build config
        run: >
          cachix watch-exec rprecenth nix -- run github:Mic92/nix-fast-build -- --no-nom --skip-cached --flake .#homeConfigurations.test.activationPackage
